let okvir1 = document.getElementById("okvir1");
iscrtajRaspored(okvir1,["Ponedjeljak","Utorak","Srijeda","Četvrtak","Petak"],8,21);
dodajAktivnost(okvir1,"WT","predavanje",9,12,"Ponedjeljak");
dodajAktivnost(okvir1,"WT","vjezbe",12,13.5,"Ponedjeljak");
dodajAktivnost(okvir1,"RG","predavanje",14,16.5,"Ponedjeljak");
dodajAktivnost(okvir1,"WT","predavanje",9,12,"Ponedjeljak");
dodajAktivnost(okvir1,"WT","predavanje",6,7,"Ponedjeljak");
dodajAktivnost(okvir1,"DM","tutorijal",9,10.5,"Utorak");
dodajAktivnost(okvir1,"DM","predavanje",9,12,"Srijeda");
dodajAktivnost(okvir1,"OIS","tutorijal",17,18,"Ponedjeljak");

let okvir2 = document.getElementById("okvir2");
iscrtajRaspored(okvir2,["Ponedjeljak","Utorak","Srijeda","Četvrtak"],10,16);
dodajAktivnost(okvir2,"OOI","predavanje",10,12,"Ponedjeljak");
dodajAktivnost(okvir2,"RPR","vjezbe",12,13.5,"Četvrtak");
dodajAktivnost(okvir2,"VVS","predavanje",14,16,"Četvrtak");
dodajAktivnost(okvir2,"WT","predavanje",9,19,"Srijeda");
dodajAktivnost(okvir2,"WT","predavanje",6,12,"Utorak");
dodajAktivnost(okvir2,"PJP","tutorijal",10.5,11.5,"Utorak");
dodajAktivnost(okvir2,"PJP","tutorijal",10.5,18.5,"Utorak");
dodajAktivnost(okvir2,"PJP","tutorijal",11,18,"Utorak");